# Generated by Django 4.0 on 2022-01-13 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etudes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noter',
            name='valide',
        ),
        migrations.CreateModel(
            name='Resultat',
            fields=[
                ('idRes', models.BigAutoField(primary_key=True, serialize=False)),
                ('decision', models.CharField(max_length=10)),
                ('numEtu', models.ForeignKey(db_column='numEtu', on_delete=django.db.models.deletion.RESTRICT, to='etudes.etudiant')),
            ],
            options={
                'db_table': 'RESULTAT',
            },
        ),
    ]
